/*

# Script: Magnitude Analysis

Script Purpose:
This script analyzes the magnitude and distribution of key business
metrics across various dimensions.

```
The analysis quantifies customers, products, sales, and revenue by
different business attributes to identify concentration, distribution,
and overall business composition.

The analysis supports:
    • Customer distribution analysis.
    • Product portfolio evaluation.
    • Revenue distribution analysis.
    • Geographic performance analysis.
    • Business segmentation and reporting.
```

===============================================================================
*/

/*=============================================================================
Customer Distribution by Country
Measure the number of customers in each country.
=============================================================================*/

SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

/*=============================================================================
Customer Distribution by Gender
Analyze customer composition by gender.
=============================================================================*/

SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

/*=============================================================================
Product Distribution by Category
Determine the number of products within each category.
=============================================================================*/

SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

/*=============================================================================
Average Product Cost by Category
Evaluate the average product cost across categories.
=============================================================================*/

SELECT
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

/*=============================================================================
Revenue Contribution by Product Category
Calculate total revenue generated by each product category.
=============================================================================*/

SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

/*=============================================================================
Customer Revenue Analysis
Measure total revenue generated by each customer.
=============================================================================*/

SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

/*=============================================================================
Product Demand by Country
Analyze the distribution of sold quantities across countries.
=============================================================================*/

SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
