/*
===============================================================================
Script: Part-to-Whole Analysis
===============================================================================

Script Purpose:
    This script evaluates the contribution of individual product categories
    to overall business sales.

    Part-to-whole analysis helps measure the relative importance of each
    category by comparing its sales contribution against total company
    revenue.

    The analysis supports:
        • Revenue contribution analysis.
        • Category performance evaluation.
        • Portfolio assessment.
        • Business concentration analysis.
        • Executive KPI reporting.

===============================================================================
*/


/*=============================================================================
    Category Contribution to Total Sales

    Calculate:
        • Total sales generated by each product category.
        • Overall company sales.
        • Percentage contribution of each category to total revenue.

    This analysis identifies which categories drive the largest portion
    of business revenue.
=============================================================================*/

WITH category_sales AS
(
    SELECT
        p.category,
        SUM(f.sales_amount) AS total_sales

    FROM gold.fact_sales f

    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key

    GROUP BY p.category
)

SELECT
    category,
    total_sales,

    SUM(total_sales) OVER () AS overall_sales,

    ROUND(
        (
            CAST(total_sales AS FLOAT)
            / SUM(total_sales) OVER ()
        ) * 100,
        2
    ) AS percentage_of_total

FROM category_sales

ORDER BY total_sales DESC;
